version: "3.8"
services:
  postgres:
    extends:
      file: ./shared/docker/postgres.yaml
      service: postgres

  minio:
    extends:
      file: ./shared/docker/minio.yaml
      service: minio

  ms-images:
    container_name: ms-images
    build:
      context: ms-images
      dockerfile: Dockerfile.dev
    env_file:
      - ./ms-images/src/.env
    ports:
      - 3333:3333
    depends_on:
      - postgres
    networks:
      - code_image_converter
    volumes: 
        - ./ms-images/src:/app

networks:
  code_image_converter:
    driver: bridge
