global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "minio"
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
      - targets: ["minio:9000"]

  - job_name: "rabbitmq"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "postgres"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["postgres-prometheus-exporter:9187"]
