version: "3.8"
services:
  prometheus:
    container_name: shared-prometheus
    image: prom/prometheus:v2.45.0
    restart: unless-stopped
    ports:
        - 9090:9090
    networks: 
        - code_image_converter
    volumes: 
        - ../data/prometheus_data:/data
        - ./config.yaml:/etc/prometheus/prometheus.yml

volumes:
  prometheus_data: {}

