version: "3.8"
services:
  postgres:
    extends:
      file: postgres.yaml
      service: postgres

  postgres-prometheus-exporter:
    extends:
      file: postgres.yaml
      service: postgres-prometheus-exporter

  minio:
    extends:
      file: minio.yaml
      service: minio

  rabbitmq:
    extends:
      file: ./rabbitmq/rabbitmq.yaml
      service: rabbitmq

  prometheus:
    extends:
      file: ./prometheus/prometheus.yaml
      service: prometheus

  grafana:
    extends:
      file: grafana.yaml
      service: grafana

networks:
  code_image_converter:
    driver: bridge
