version: "3.8"
services:
  postgres:
    extends:
      file: postgres.yaml
      service: postgres

  minio:
    extends:
      file: minio.yaml
      service: minio

  rabbitmq:
    extends:
      file: rabbitmq.yaml
      service: rabbitmq

networks:
  code_image_converter:
    driver: bridge
