version: "3.8"
services:
  loki:
    container_name: shared-loki
    image: grafana/loki:2.8.2
    # restart: unless-stopped
    ports:
      - 3100:3100
    networks: 
      - code_image_converter
    volumes: 
      - ./data/loki_data:/loki
    user: "0"

volumes:
  loki_data: {}