version: "3.8"
services:
  minio:
    container_name: shared-minio
    image: minio/minio:RELEASE.2023-06-23T20-26-00Z
    restart: always
    environment:
        - MINIO_ROOT_USER=minio
        - MINIO_ROOT_PASSWORD=minio123
        - MINIO_PROMETHEUS_AUTH_TYPE=public
    ports:
        - 9000:9000
    networks: 
        - code_image_converter
    volumes: 
        - ./data/minio_data:/data
    command: minio server /data

volumes:
  minio_data: {}
