version: "3.8"
services:
  postgres:
    container_name: shared-postgres
    image: postgres:15.3
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5442:5432
    networks: 
        - code_image_converter
    volumes: 
        - ./data/postgres_data:/var/lib/postgresql/data

  postgres-prometheus-exporter:
    container_name: shared-postgres-prom
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME="postgresql://postgres:postgres@postgres:5432"
    ports:
      - 9187:9187
    networks: 
      - code_image_converter

volumes:
  postgres_data: {}
